### ISSUE TITLE
does not create log file

### ISSUE THREAD

**Issue by burrbull** [crlf0710/tectonic#118]
Writes "Transcript written on test.log.", but file is absent.

**Comment by crlf0710** [comment]
I thought only when --keep-intermediate-files is turned on will that file be kept, no?

**Comment by burrbull** [comment]
Maybe. So why then it writes misleading text?

**Comment by cormacrelf** [comment]
Because the engine has no idea whether the file is being written or not. Best to leave as is so output can be identical I guess. (Although there are many improvements to be made to xetex error output, not least the awful line-splitting to indicate where an error occurred, so not sure if that’s a great general position. We have already changed it with panics, but no test cases should panic. Maybe it doesn’t matter if using updatable snapshot testing.)
