### ISSUE TITLE
`latex_to_pdf` test breaks

### ISSUE THREAD

**Issue by burrbull** [crlf0710/tectonic#258]
```
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.44.0-nightly (14b15521c 2020-04-23)
```
Ubuntu 20.04

```
arfbuzz-icu" "-lharfbuzz" "-licuuc" "-licudata" "-lfreetype" "-lgraphite2" "-lfreetype" "-lpng16" "-lz" "-lssl" "-lcrypto" "-lutil" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil"
  = note: /usr/bin/ld: /media/music/builds/tectonic/debug/deps/libtectonic_engine-9b7d331bf15c1de6.rlib(stub_icu.o): undefined reference to symbol 'ubidi_open_66'
          /usr/bin/ld: /lib/x86_64-linux-gnu/libicuuc.so.66: ошибка добавления символов: DSO missing from command line
          collect2: error: ld returned 1 exit status      
```

**Comment by burrbull** [comment]
cc @pkgw 
@crlf0710

**Comment by crlf0710** [comment]
Let me find a linux machine to see if i can reproduce this.

**Comment by crlf0710** [comment]
Mmm, it builds fine on my linux machine. Mine is using Arch distro though. I think there's some `icu` version mismatch going on here. Do you have multiple icu versions installed, or maybe even a `cargo clean` helps?

**Comment by ratmice** [comment]
Hmm, be nice to make a copy of the target directory before clean, so we can try and come up with a fix, https://github.com/tectonic-typesetting/tectonic/issues/138 is basically the same.

I wonder if it helps adding the .pc files to the [cargo:rerun-if-changed=path](https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorerun-if-changedpath), I'm not sure how to test if that would be the case since modifying build.rs should probably trigger a rerun?

From the `pkg-config` program, the `--path` argument will give you the `.pc` file.
We'd need to extend the `pkg_config` crate to expose that (I believe at least, as I don't see it).

Additionally i'm not sure if `rerun-if-changed` can take a path outside the build dir, It doesn't say it can't.
It also doesn't really help if there is a file added to an earlier entry in PKG_CONFIG_PATH.
but it might catch the case where a system-lib is changed.

:shrug:

**Comment by burrbull** [comment]
`cargo clean` doesn't help.

master https://github.com/tectonic-typesetting/tectonic compiles fine.

```
➜  tectonic git:(oxidize) ls /lib/x86_64-linux-gnu/libicuuc.so*
/lib/x86_64-linux-gnu/libicuuc.so     /lib/x86_64-linux-gnu/libicuuc.so.66.1
/lib/x86_64-linux-gnu/libicuuc.so.66
➜  tectonic git:(oxidize) 
```

**Comment by burrbull** [comment]
This is first commit with the issue:
https://github.com/crlf0710/tectonic/commit/4fef69f0cb74b7fdd780e0dfe5cd77cffd6e73e2

**Comment by crlf0710** [comment]
Hey, this is tricky... The only change in that libpng version bump is 
https://github.com/kornelski/rust-libpng-sys/commit/89a8ff64b8f34f7a70adbfb9a52fbc05366cdf81
Which seems harmless...

**Comment by burrbull** [comment]
And this small change breaks build on Ubuntu 20.04. I don't know why.

**Comment by ratmice** [comment]
Really strange... I tried to figure out a way to get more information out of the linker,
supposedly `RUSTC_LOG="rustc_trans=info"` at some point dumped linker output,
and `RUSTFLAGS="-Z print-link-args --C link-arg=-Wl,--verbose"` (alternately `-Wl,-V`) should cause the linker to dump a bunch of extra info, but when adding those even with `cargo build -vv`, I never see any linker output.

If we could get `-Wl,-V` output for the working/failing runs that'd at least give us something to compare... perhaps someone else knows how to make that work?

**Comment by crlf0710** [comment]
@burrbull Do you feel we should land #260 ? I don't object. However i'd like to keep this issue open, until we finally found the root cause.

**Comment by burrbull** [comment]
I think so.

Also someone should fix MAC link error.
I can't do this.

**Comment by burrbull** [comment]
And what with `tectonic_on_arxiv`?

Can we run this check again?

**Comment by XVilka** [comment]
Maybe it is possible to run it with GitHub Actions? They are certainly faster than Travis.

**Comment by burrbull** [comment]
Помощи всегда рады 😉
