### ISSUE TITLE
[Discussion]Move dpx(dvipdfmx) into its own crate.

### ISSUE THREAD

**Issue by crlf0710** [crlf0710/tectonic#49]
I think i want to separate the dvipdfmx code into its own crate, and mark the license of that single crate to be GPL, since the original c code's license is that.

I'd like to hear what others think about this, especially @pkgw .

**Comment by pkgw** [comment]
It would be good to get this right. One thing to think about is that both the dvipdfmx code and the main XeTeX engine rely on a common library of C routines for interfacing with the foundations provided by Tectonic (I/O, etc.). Those would probably need to be moved to a different new crate so that they could be shared.

In my experience, this stuff then becomes complicated because sharing C headers between different Rust crates is hard ... which much less of an issue if everything gets Rust-ified!

As a side note, I am happy to host some of these issues and PRs in the main `tectonic-typesetting` GitHub repos ... some of the things coming up here seem like they could be orthogonal to the C-to-Rust effort. But I see that you're using the Projects feature here, which might explain the motivation? Anyway, nothing urgent on this topic, but if discussions start really splintering between this fork and the main organization I'd like to think about ways to reduce/avoid that.

**Comment by crlf0710** [comment]
@pkgw My intention is that once the Rustified version get stable enough, we can upstream the Rust version back to the main repo. Or maybe earlier than that, and make it a side-by-side configuration using crate features or things like that. Which way do you feel better?

**Comment by burrbull** [comment]
Maybe start from separating in `dpx` module?

**Comment by mulimoen** [comment]
Would the crate be useful outside of tectonic?

**Comment by crlf0710** [comment]
The dpx library's functionality is generating pdf file from dvi data. DVI is an largely obsolete file format, according to wikipedia these's no viewer available now. However this library contains some useful code for pdf generation, which i think is a current feature gap in rust eco-system... But the library license is GPL :( which makes it less appealing at least to myself.

**Comment by crlf0710** [comment]
Done in #59
